"""Bootstrap a new tenant site — generate the SQL migration and a
Phase-1B checklist.

Encodes every landmine surfaced in the pixelmatch.art rollout (see
docs/NEW-SITE-PLAYBOOK.md retro) so the next site doesn't re-discover
them. Output is just text:
  1. A migration SQL block (paste into Supabase SQL Editor)
  2. A printed checklist of remaining manual steps

This script DOES NOT touch the DB or filesystem on its own — schema
changes need operator approval per the "不修改 schema" boundary.

Usage:
  python -m scripts.bootstrap_new_site \
      --domain pixelmatch.art \
      --niche ecommerce_tools \
      --brand-name PixelMatch \
      --tool-url https://pixelmatch.art \
      --cta-url https://pixelmatch.art/login \
      --article-types tool_guide,vs_comparison,use_case,policy_guide \
      --budget 500
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap

# Article types that ALREADY exist in articles_article_type_check.
# Anything outside this set triggers a CHECK widen in the migration.
EXISTING_ARTICLE_TYPES = {
    # gaming (ntecodex)
    "build", "tier_list", "boss_guide", "reroll",
    "character_db", "weapon_db", "news", "faq", "comparison",
    # ecommerce (pixelmatch — added 2026-05-14)
    "tool_guide", "vs_comparison", "use_case", "policy_guide",
}


def _build_sites_jsonb(args) -> dict:
    """Mirror the canonical jsonb shape — keep every required key
    present so neither the orchestrator nor the agents blow up at
    runtime with KeyError."""
    types = [t.strip() for t in args.article_types.split(",") if t.strip()]
    return {
        "niche": args.niche,
        "brand": {
            "name": args.brand_name,
            "tagline": args.tagline or f"{args.brand_name} — autogenerated content",
            "tone": args.tone or "professional, conversion-focused",
            "tool_url": args.tool_url,
            "signup_url": args.signup_url or args.cta_url,
        },
        "cta": {
            "primary_url": args.cta_url,
            "primary_label": args.cta_label or "Get started",
        },
        "monthly_budget_usd": args.budget,
        "qa_thresholds": {
            "min_quality_score": 7.0,
            "max_retry_rounds": 1,
        },
        "text_provider": {
            "qa_model": "gemini-3.1-pro-preview",
            "outline_model": "gemini-3.1-pro-preview",
            "writing_model": "gemini-3-flash-preview",
            "keyword_research_model": "gemini-3-flash-preview",
        },
        "image_provider": {
            "provider": "gemini",
            "model": "gemini-2.5-flash-image",
            "default_aspect_ratio": "16:9",
            "fallback_provider": None,
            "extra_params": {},
        },
        "content_plan": {
            "min_word_count": args.min_words,
            "max_word_count": args.max_words,
            "daily_articles": 6,
            "type_blacklist": [],
            "diversity": {
                "required_types": types,
                "min_types_per_week": min(len(types), 3),
            },
        },
        "allowed_article_types": types,
        "ads": {"adsense_enabled": True},
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--domain", required=True, help="e.g. pixelmatch.art")
    p.add_argument("--site-name", default=None,
                   help="Human-readable name; defaults to '<Brand> Blog'")
    p.add_argument("--niche", required=True,
                   choices=["gaming", "ecommerce_tools"],
                   help="Drives which prompt family agents use")
    p.add_argument("--brand-name", required=True, help="e.g. PixelMatch")
    p.add_argument("--tool-url", required=True, help="https://pixelmatch.art")
    p.add_argument("--cta-url", required=True, help="https://pixelmatch.art/login")
    p.add_argument("--signup-url", default=None, help="Default = cta-url")
    p.add_argument("--cta-label", default=None)
    p.add_argument("--tagline", default=None)
    p.add_argument("--tone", default=None)
    p.add_argument("--article-types", required=True,
                   help="Comma-separated, e.g. tool_guide,vs_comparison,use_case,policy_guide")
    p.add_argument("--budget", type=int, default=500, help="USD/month")
    p.add_argument("--min-words", type=int, default=1400)
    p.add_argument("--max-words", type=int, default=2400)
    p.add_argument("--migration-number", default="00X",
                   help="Suffix for the generated migration filename")
    args = p.parse_args()

    types = [t.strip() for t in args.article_types.split(",") if t.strip()]
    if not types:
        print("❌ --article-types required", file=sys.stderr); return 2

    # Detect article types that need a CHECK widen.
    new_types = [t for t in types if t not in EXISTING_ARTICLE_TYPES]

    site_name = args.site_name or f"{args.brand_name} Blog"
    config = _build_sites_jsonb(args)
    config_json = json.dumps(config, indent=2)

    print("=" * 78)
    print(f"Bootstrap migration for {args.domain}")
    print("=" * 78)
    print()
    print(textwrap.dedent(f"""\
        -- Save as: src/db/migrations/{args.migration_number}_{args.domain.replace('.', '_')}_site.sql
        -- Run in Supabase SQL Editor (web UI, NOT Mac terminal).

    """))

    # CHECK constraint widen if new types
    if new_types:
        all_types_after = sorted(EXISTING_ARTICLE_TYPES | set(new_types))
        type_list_sql = ",\n    ".join(f"'{t}'" for t in all_types_after)
        print(textwrap.dedent(f"""\
            -- New article types detected: {new_types}
            -- Widening articles_article_type_check additively (safe,
            -- existing rows still pass).
            alter table articles drop constraint articles_article_type_check;
            alter table articles add constraint articles_article_type_check
              check (article_type is null or article_type = any (array[
                {type_list_sql}
              ]));
        """))
    else:
        print("-- No CHECK widen needed (all types already allowed).\n")

    # INSERT
    print(textwrap.dedent(f"""\
        -- INSERT new tenant. Idempotent: ON CONFLICT updates jsonb.
        insert into sites (id, domain, site_name, config, created_at, updated_at)
        values (
          gen_random_uuid(),
          '{args.domain}',
          '{site_name}',
          '{config_json.replace("'", "''")}'::jsonb,
          now(),
          now()
        )
        on conflict (domain) do update
           set config = excluded.config,
               site_name = excluded.site_name,
               updated_at = now();

        -- Sanity check.
        select id, domain, site_name,
               config->>'niche' as niche,
               config->'brand'->>'name' as brand,
               jsonb_array_length(config->'allowed_article_types') as types,
               (config->>'monthly_budget_usd')::int as budget
          from sites where domain = '{args.domain}';
    """))

    print("=" * 78)
    print("Next steps (manual)")
    print("=" * 78)
    print(textwrap.dedent(f"""\

        1. Paste the SQL above into Supabase SQL Editor → Run.
           Verify SELECT returns 1 row with niche={args.niche!r}.

        2. If using a new niche (not "gaming" or "ecommerce_tools"):
           - Add prompts to src/agents/_prompts_<niche>.py
           - Add `if niche == "<niche>": return self._execute_<niche>(...)`
             branch in outline.py / writing.py / qa.py
           - pytest tests/ must stay green

        3. Astro site (~90 min):
           cp -R ntecodex-site <new>-site
           cd <new>-site && rm -rf .git dist node_modules functions
           # Edit: tailwind palette, astro.config (site + base), content/config.ts
           #       Header/Footer brand, public/_redirects (if base!=/)
           # In src/agents/publish.py: add the new article_types to
           # PATH_BY_TYPE + URL_BY_TYPE (include the /blog or
           # whatever base prefix in URL_BY_TYPE).
           npm install && npm run build  # must succeed
           git init -b main && gh repo create JeffZ911/<new>-site --private --source=.
           git add . && git commit -m "skeleton" && git push -u origin main

        4. Cloudflare Pages:
           cd <new>-site
           npx wrangler pages project create <new>-blog --production-branch main
           npx wrangler pages deploy dist --project-name <new>-blog --branch main
           # In dashboard: Custom domains → blog.{args.domain} →
           # "Begin CNAME setup" (NOT DNS transfer).
           # At DNS provider: CNAME blog → <new>-blog.pages.dev
           # Delete any conflicting A record or URL Forwarding on blog subdomain.

        5. Smoke (~20 min):
           cd traffic-ops-core && source .venv/bin/activate
           python -m scripts.seed_keywords_for_<niche> --count 60 --dry-run
           # check distribution; if good, drop --dry-run
           SITE_DOMAIN={args.domain} SITE_REPO_PATH=~/Documents/traffic-ops/<new>-site \\
             python -m scripts.run_batch_smoke --count 1 --max-retries 1
           SITE_DOMAIN={args.domain} SITE_REPO_PATH=~/Documents/traffic-ops/<new>-site \\
             python -m scripts.publish_articles
           SITE_DOMAIN={args.domain} SITE_REPO_PATH=~/Documents/traffic-ops/<new>-site \\
             python -m scripts.run_image_for_articles --new-only --inline 6 --budget-usd 0.50
           cd ~/Documents/traffic-ops/<new>-site && git add . && git commit && git push

        6. Chrome MCP UX audit on blog.{args.domain}:
           - All CTAs point at {args.cta_url} (not /signup etc.)
           - Comments widget shows or is hidden (not "failed to load")
           - SourceList not duplicated (writer ## Sources already in body)
           - Footer links return 200 on target SaaS
           - No console errors / failed network requests

        7. GitHub Actions cron:
           Copy .github/workflows/content_pixelmatch.yml → content_<new>.yml
           - SITE_DOMAIN: {args.domain}
           - PAT secret: <NEW>_SITE_REPO_PAT (fine-grained, contents:write on the site repo)
           Test: gh workflow run content_<new>.yml

        8. AdSense (after ≥10 articles): add blog.{args.domain} in
           AdSense console → request review.

    """))

    print(f"Done. See docs/NEW-SITE-PLAYBOOK.md for the full retrospective.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
