"""One-shot: bootstrap quvii.com into the traffic-ops DB.

Inserts the `sites` row (if missing) and seeds an initial 50-keyword pool
across security-camera buyer queries. After this runs once, the daily
content_quvii cron has enough fuel for its first ~2 weeks before
keyword_gardener's affiliate-seed loop takes over.

Idempotent — re-running is safe (uses INSERT ... ON CONFLICT and
case-insensitive keyword dedup).

Usage (via workflow_dispatch on GitHub Actions):
    Actions tab → "Bootstrap quvii.com (one-shot)" → Run workflow
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

from dotenv import load_dotenv
from src.db.client import get_db_connection

load_dotenv(Path(__file__).resolve().parent.parent / ".env")


SITE_DOMAIN = "quvii.com"

SITE_CONFIG = {
    "niche": "security_cameras",
    "brand": {
        "name": "Quvii",
        "slogan": "See everything. Subscribe to nothing.",
    },
    "site_name": "Quvii",
    "monthly_budget_usd": 200,   # start modest; ramp after first sales prove ROI
    "content_plan": {
        "min_word_count": 1200,
        "max_word_count": 2200,
        # 5 floor types across the 4 collections = daily presence everywhere
        "daily_article_cap": 6,
        "article_type_floors": {
            "camera_buying_guide":  2,  # affiliate funnel — most revenue-relevant
            "camera_comparison":    1,  # vs-Eufy/Ring/Reolink mid-funnel
            "camera_install":       1,  # how-to (low competition, high intent)
            "camera_troubleshoot":  1,  # steal competitor frustrations
            "camera_learn":         1,  # pillar growth
        },
        "type_blacklist": [],  # no blacklist at launch
    },
    "text_provider": {
        "provider": "gemini",
        "writing_model":          "gemini-3-flash-preview",
        "qa_model":               "gemini-3.1-pro-preview",
        "outline_model":          "gemini-3-flash-preview",
        "keyword_research_model": "gemini-3.1-flash-lite",
        "report_summary_model":   "gemini-3-flash-preview",
    },
    "image_provider": {
        "provider": "gemini",
        "model":    "gemini-3.1-flash-image-preview",
    },
    # Restrict KeywordSelector to security-camera article_types only.
    # Without this it'd consider gaming types like "boss_guide" too.
    "allowed_article_types": [
        "camera_buying_guide",
        "camera_comparison",
        "camera_install",
        "camera_troubleshoot",
        "camera_news",
        "camera_learn",
        "camera_review",
        "camera_support",
    ],
    "qa_thresholds": {
        "min_quality_score": 6.0,
    },
}


# 50 seed keywords across the 5 floor categories + camera_review.
# Generated by hand for the launch — keyword_gardener takes over with
# AI-generated seeds within 24h of first cron.
SEED_KEYWORDS: list[dict] = [
    # ─────────── camera_buying_guide (revenue funnel) ───────────
    {"kw": "best wireless security camera for renters under 100", "atype": "camera_buying_guide", "audience": "renters", "intent": "buy"},
    {"kw": "best outdoor security camera without subscription",   "atype": "camera_buying_guide", "audience": "anti_subscription", "intent": "buy"},
    {"kw": "best wired security camera system for small business",    "atype": "camera_buying_guide", "audience": "small_business", "intent": "buy"},
    {"kw": "best floodlight camera for driveway 2026",             "atype": "camera_buying_guide", "audience": "homeowner", "intent": "buy"},
    {"kw": "best indoor security camera for pet monitoring",       "atype": "camera_buying_guide", "audience": "pet_owners", "intent": "buy"},
    {"kw": "best poe security camera system for home",             "atype": "camera_buying_guide", "audience": "diy_install", "intent": "buy"},
    {"kw": "best wireless camera that works without wifi",         "atype": "camera_buying_guide", "audience": "off_grid", "intent": "buy"},
    {"kw": "best 4k security camera under 200",                    "atype": "camera_buying_guide", "audience": "value_buyer", "intent": "buy"},
    {"kw": "best battery powered outdoor camera for cabin",         "atype": "camera_buying_guide", "audience": "remote_property", "intent": "buy"},
    {"kw": "best doorbell camera that records locally",            "atype": "camera_buying_guide", "audience": "privacy_first", "intent": "buy"},
    # ─────────── camera_comparison (head-to-head) ───────────
    {"kw": "eufy vs ring security camera honest comparison",       "atype": "camera_comparison", "audience": "indecisive", "intent": "research"},
    {"kw": "reolink vs amcrest poe camera",                        "atype": "camera_comparison", "audience": "technical", "intent": "research"},
    {"kw": "arlo pro vs ring stick up cam",                        "atype": "camera_comparison", "audience": "mid_market", "intent": "research"},
    {"kw": "blink vs wyze outdoor camera 2026",                    "atype": "camera_comparison", "audience": "budget", "intent": "research"},
    {"kw": "eufy solocam vs ring solar",                           "atype": "camera_comparison", "audience": "off_grid", "intent": "research"},
    {"kw": "google nest cam vs ring stick up cam",                 "atype": "camera_comparison", "audience": "smart_home", "intent": "research"},
    {"kw": "ring vs eufy doorbell privacy comparison",             "atype": "camera_comparison", "audience": "privacy_first", "intent": "research"},
    {"kw": "lorex vs reolink nvr system",                          "atype": "camera_comparison", "audience": "technical", "intent": "research"},
    # ─────────── camera_install (how-to) ───────────
    {"kw": "how to install outdoor camera without drilling",       "atype": "camera_install", "audience": "renters", "intent": "how-to"},
    {"kw": "how to install poe security camera step by step",      "atype": "camera_install", "audience": "diy_install", "intent": "how-to"},
    {"kw": "how to install doorbell camera in apartment",          "atype": "camera_install", "audience": "renters", "intent": "how-to"},
    {"kw": "how to mount outdoor camera on vinyl siding",          "atype": "camera_install", "audience": "homeowner", "intent": "how-to"},
    {"kw": "how to install camera without existing wiring",        "atype": "camera_install", "audience": "diy_install", "intent": "how-to"},
    {"kw": "how to set up security camera with alexa",             "atype": "camera_install", "audience": "smart_home", "intent": "how-to"},
    {"kw": "how to install camera in garage without internet",     "atype": "camera_install", "audience": "off_grid", "intent": "how-to"},
    # ─────────── camera_troubleshoot (steal competitor frustration) ───────────
    {"kw": "ring camera keeps disconnecting from wifi fix",        "atype": "camera_troubleshoot", "audience": "ring_owners", "intent": "fix"},
    {"kw": "eufy camera night vision blurry fix",                  "atype": "camera_troubleshoot", "audience": "eufy_owners", "intent": "fix"},
    {"kw": "blink camera not detecting motion",                    "atype": "camera_troubleshoot", "audience": "blink_owners", "intent": "fix"},
    {"kw": "arlo camera battery draining fast",                    "atype": "camera_troubleshoot", "audience": "arlo_owners", "intent": "fix"},
    {"kw": "reolink camera offline error fix",                     "atype": "camera_troubleshoot", "audience": "reolink_owners", "intent": "fix"},
    {"kw": "wyze camera app keeps crashing",                       "atype": "camera_troubleshoot", "audience": "wyze_owners", "intent": "fix"},
    {"kw": "nest camera not recording motion events",              "atype": "camera_troubleshoot", "audience": "nest_owners", "intent": "fix"},
    {"kw": "outdoor camera not working in cold weather",           "atype": "camera_troubleshoot", "audience": "cold_climate", "intent": "fix"},
    # ─────────── camera_learn (pillar deep-dives) ───────────
    {"kw": "what is poe camera and how does it work",              "atype": "camera_learn", "audience": "beginner", "intent": "informational"},
    {"kw": "rtsp vs onvif camera protocol explained",              "atype": "camera_learn", "audience": "technical", "intent": "informational"},
    {"kw": "are wireless cameras safe from hackers",               "atype": "camera_learn", "audience": "privacy_first", "intent": "informational"},
    {"kw": "how home security cameras store footage explained",    "atype": "camera_learn", "audience": "beginner", "intent": "informational"},
    {"kw": "camera resolution explained 2k vs 4k difference",      "atype": "camera_learn", "audience": "shopper", "intent": "informational"},
    {"kw": "how night vision security cameras work",               "atype": "camera_learn", "audience": "beginner", "intent": "informational"},
    {"kw": "do security cameras need internet to record",          "atype": "camera_learn", "audience": "shopper", "intent": "informational"},
    {"kw": "are security cameras worth it for apartment",          "atype": "camera_learn", "audience": "renters", "intent": "informational"},
    # ─────────── camera_review (own + competitor reviews) ───────────
    {"kw": "eufy solocam s40 long term review",                    "atype": "camera_review", "audience": "indecisive", "intent": "research"},
    {"kw": "ring stick up cam pro honest review",                  "atype": "camera_review", "audience": "ring_curious", "intent": "research"},
    {"kw": "reolink rlc 810a review 4k poe",                       "atype": "camera_review", "audience": "technical", "intent": "research"},
    {"kw": "blink outdoor 4 long term review",                     "atype": "camera_review", "audience": "budget", "intent": "research"},
    {"kw": "arlo pro 5 review 2026",                               "atype": "camera_review", "audience": "mid_market", "intent": "research"},
    {"kw": "wyze cam v4 worth it review",                          "atype": "camera_review", "audience": "budget", "intent": "research"},
    # ─────────── camera_news (when industry breaks) — seed light ───────────
    {"kw": "ring 2026 subscription price changes",                 "atype": "camera_news", "audience": "ring_owners", "intent": "informational"},
    {"kw": "eufy cloud upload controversy update",                 "atype": "camera_news", "audience": "privacy_first", "intent": "informational"},
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    with get_db_connection() as conn, conn.cursor() as cur:
        # 1) Sites row — INSERT if missing, else update config to current
        cur.execute("select id, config from sites where domain=%s", (SITE_DOMAIN,))
        row = cur.fetchone()
        if row:
            site_id = str(row[0])
            print(f"  ✓ site {SITE_DOMAIN} exists ({site_id}) — updating config")
            if not args.dry_run:
                cur.execute(
                    "update sites set config=%s, updated_at=now() where id=%s",
                    (json.dumps(SITE_CONFIG), site_id),
                )
        else:
            site_id = str(uuid.uuid4())
            print(f"  ⚙ inserting new site {SITE_DOMAIN} ({site_id})")
            if not args.dry_run:
                cur.execute(
                    """
                    insert into sites (id, domain, status, config, site_name)
                    values (%s, %s, 'active', %s, %s)
                    """,
                    (site_id, SITE_DOMAIN, json.dumps(SITE_CONFIG), SITE_CONFIG["site_name"]),
                )

        # 2) Existing keywords (case-insensitive dedup)
        cur.execute("select lower(keyword) from keywords where site_id=%s", (site_id,))
        existing = {r[0] for r in cur.fetchall()}

        to_insert = []
        for kw in SEED_KEYWORDS:
            text = kw["kw"]
            if text.lower() in existing:
                continue
            notes = (
                f"article_type={kw['atype']}|"
                f"audience={kw['audience']}|"
                f"game=multi|"
                f"[bootstrap_quvii seed]"
            )[:500]
            to_insert.append(
                (site_id, text, kw["intent"], 70, "bootstrap_quvii", notes)
            )

        print(f"  ⚙ {len(to_insert)} new keywords to insert "
              f"({len(SEED_KEYWORDS) - len(to_insert)} duplicates skipped)")

        if not args.dry_run and to_insert:
            cur.executemany(
                """
                insert into keywords
                  (site_id, keyword, intent, priority_score, source, notes, status)
                values (%s, %s, %s, %s, %s, %s, 'planned')
                """,
                to_insert,
            )

        if args.dry_run:
            print("DRY RUN — no DB writes performed.")
        else:
            print("✓ bootstrap complete. content_quvii cron can run now.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
