"""imade4u keyword top-up — seasonal (QDF) + evergreen pillar refill.

Gift demand is CALENDAR-driven, so this is more deterministic than news trends:
- Seasonal: when a gift occasion is within the horizon, seed occasion topics
  with a HIGH, proximity-boosted priority so the pipeline publishes them
  4-6 weeks ahead of the peak (the QDF window for gifts).
- Evergreen: keep the planned pool fed (pet memorial / sympathy / recipient /
  buying / how-to) so a 3-4/day cadence never starves.

Topics are generated by Gemini (DISTINCT titles, grounded in the store's real
product categories), deduped against the existing pool, and inserted with
notes `type=<pillar>|match=<products>|tags=<tags>` for content_imade4u.

Usage:
  python -m scripts.gift_keywords                 # top-up if pool is low
  python -m scripts.gift_keywords --force --target 20
"""
from __future__ import annotations

import argparse
import json
from datetime import date

from dotenv import load_dotenv

from src.db.client import get_db_connection
from src.utils.llm import get_llm_provider

load_dotenv()

# Product categories (real, from the catalog) the writer can build guides around.
PRODUCT_CATS = ("custom necklaces, name necklaces, photo projection necklaces, "
                "personalized bracelets, custom rings, engraved keychains, custom "
                "photo mugs, pet portraits, pet memorials, custom pillows, blankets, "
                "ornaments, wall art & canvas, wooden signs, phone cases, baby gifts")

# Gift calendar (US): occasion → (month, day), lead weeks to start publishing.
GIFT_CALENDAR = [
    ("Valentine's Day", (2, 14), 6), ("Mother's Day", (5, 10), 6),
    ("Father's Day", (6, 21), 5), ("Graduation season", (5, 25), 5),
    ("Back to School", (8, 20), 4), ("Halloween", (10, 31), 4),
    ("Thanksgiving", (11, 26), 4), ("Black Friday & Cyber Monday", (11, 27), 5),
    ("Christmas", (12, 25), 7),
]


def _upcoming(today: date, horizon_weeks: int = 8) -> list[str]:
    out = []
    for name, (m, d), lead in GIFT_CALENDAR:
        for yr in (today.year, today.year + 1):
            try:
                occ = date(yr, m, d)
            except ValueError:
                continue
            weeks = (occ - today).days / 7.0
            if 0 <= weeks <= horizon_weeks:
                out.append(name)
                break
    return out


PROMPT = """You are an SEO content planner for iMade4U, a store of PERSONALIZED
gifts. Generate {n} DISTINCT, specific gift-guide blog topics — each a unique
angle (occasion, recipient, product type, or REAL-TIME TREND). No near-dupes.

Ground every topic in these real product categories:
  {cats}

USE GOOGLE SEARCH to weave in what is ACTUALLY TRENDING RIGHT NOW in gifting
(last ~30 days): viral / TikTok-famous personalized gift types, pop-culture or
news-driven gifting moments, "{year} gift trends", surging gift searches. Make
~1/3 of the topics these real, current trends (mark them type=occasion_guide or
buying_guide, priority 80-90). Only use a trend you can back with a real source.

{seasonal}

Pillars (article_type): occasion_guide, recipient_guide, pet_memorial,
sympathy_guide, buying_guide, how_to.

Do NOT duplicate these existing topics (case-insensitive):
{existing}

Reply ONLY with a JSON array (no markdown fence), each element:
{{"title": "<specific blog title, 50-70 chars>",
  "type": "<one pillar>",
  "match": "<2-4 SHORT single-word product nouns to pick products, e.g. necklace, mug, keychain — NOT phrases like 'custom photo mug'>",
  "tags": "<2-4 comma article tags, lowercase-hyphen>",
  "is_trend": <true if this is a REAL-TIME/viral/news/cultural trend; false for evergreen or fixed-calendar topics>,
  "priority": <integer 60-90; trending/seasonal/high-intent higher>}}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", type=int, default=15)
    ap.add_argument("--min-planned", type=int, default=12)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--model", default="gemini-3-flash-preview")
    args = ap.parse_args()

    with get_db_connection() as conn, conn.cursor() as cur:
        cur.execute("select id from sites where domain='imade4u.com'")
        row = cur.fetchone()
        if not row:
            print("❌ imade4u tenant missing"); return 2
        site_id = str(row[0])
        cur.execute("select count(*) from keywords where site_id=%s and status='planned'", (site_id,))
        planned = cur.fetchone()[0]
        cur.execute("select keyword from keywords where site_id=%s order by created_at desc limit 60", (site_id,))
        existing = [r[0] for r in cur.fetchall()]

    if planned >= args.min_planned and not args.force:
        print(f"  pool healthy ({planned} planned ≥ {args.min_planned}) — no top-up"); return 0

    occ = _upcoming(date.today())
    seasonal = (f"SEASONAL FOCUS — these gift occasions are approaching; weight "
                f"~half the topics toward them with priority 80-90: {', '.join(occ)}."
                if occ else "No major gift occasion is imminent; focus on evergreen "
                "pillars (pet memorial, sympathy, recipient, buying guides).")
    prompt = PROMPT.format(n=args.target, cats=PRODUCT_CATS, seasonal=seasonal,
                           year=date.today().year,
                           existing="\n".join(f"  - {k}" for k in existing[:50]) or "  (none)")

    # Self-improvement loop: inject the latest AI guidance (from qdf_report's
    # retrospective on how imade4u's trend pages performed) so topic selection
    # learns what actually wins traffic.
    try:
        from src.utils.qdf_memory import latest_qdf_guidance
        g = latest_qdf_guidance(site_id)
        if g:
            prompt += ("\n\nLEARNINGS FROM OUR RECENT PERFORMANCE (apply these — "
                       "derived from how our last gift trend posts actually did):\n" + g + "\n")
            print("   🧠 injected prior QDF guidance")
    except Exception:
        pass

    # enable_search → real current gift trends (grounding forces json_mode off;
    # the parse below handles fenced / array output).
    resp = get_llm_provider("gemini").generate(
        prompt=prompt, model=args.model, max_tokens=4000, temperature=0.7,
        json_mode=False, enable_search=True)
    text = (resp.text or "").strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0]
    try:
        data = json.loads(text)
    except Exception:
        i, j = text.find("["), text.rfind("]")
        data = json.loads(text[i:j + 1]) if i >= 0 else []
    if isinstance(data, dict):
        data = next((v for v in data.values() if isinstance(v, list)), [])

    have = {k.lower() for k in existing}
    nonrend = "gift_seasonal" if occ else "gift_topup"
    inserted = ntrend = 0
    valid_types = {"occasion_guide", "recipient_guide", "pet_memorial",
                   "sympathy_guide", "buying_guide", "how_to"}
    with get_db_connection(autocommit=True) as conn, conn.cursor() as cur:
        for it in data:
            if not isinstance(it, dict):
                continue
            title = (it.get("title") or "").strip()
            atype = it.get("type") if it.get("type") in valid_types else "buying_guide"
            if not title or title.lower() in have or not it.get("match"):
                continue
            # Real-time trends → source='trend' so qdf_report tracks them and
            # the AI retrospective loop can learn from their performance.
            row_src = "trend" if it.get("is_trend") else nonrend
            notes = f"type={atype}|match={it.get('match')}|tags={it.get('tags','personalized-gifts')}"
            cur.execute(
                "insert into keywords (site_id, keyword, intent, priority_score, source, notes, status) "
                "values (%s,%s,'commercial',%s,%s,%s,'planned') on conflict (site_id, keyword) do nothing",
                (site_id, title, int(it.get("priority") or 65), row_src, notes))
            if cur.rowcount:
                inserted += 1
                if row_src == "trend":
                    ntrend += 1
                have.add(title.lower())
    print(f"  ✓ imade4u top-up: +{inserted} topics ({ntrend} real-time trend, "
          f"{'seasonal: '+', '.join(occ) if occ else 'evergreen'}) cost ${resp.cost_usd:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
