"""imade4u keyword top-up — seasonal (QDF) + evergreen pillar refill.

Gift demand is CALENDAR-driven, so this is more deterministic than news trends:
- Seasonal: when a gift occasion is within the horizon, seed occasion topics
  with a HIGH, proximity-boosted priority so the pipeline publishes them
  4-6 weeks ahead of the peak (the QDF window for gifts).
- Evergreen: keep the planned pool fed (pet memorial / sympathy / recipient /
  buying / how-to) so a 3-4/day cadence never starves.

Topics are generated by Gemini (DISTINCT titles, grounded in the store's real
product categories), deduped against the existing pool, and inserted with
notes `type=<pillar>|match=<products>|tags=<tags>` for content_imade4u.

Usage:
  python -m scripts.gift_keywords                 # top-up if pool is low
  python -m scripts.gift_keywords --force --target 20
"""
from __future__ import annotations

import argparse
import json
from datetime import date

from dotenv import load_dotenv

from src.db.client import get_db_connection
from src.utils.llm import get_llm_provider

load_dotenv()

# Product categories (real, from the catalog) the writer can build guides around.
PRODUCT_CATS = ("custom necklaces, name necklaces, photo projection necklaces, "
                "personalized bracelets, custom rings, engraved keychains, custom "
                "photo mugs, pet portraits, pet memorials, custom pillows, blankets, "
                "ornaments, wall art & canvas, wooden signs, phone cases, baby gifts")

# Gift calendar (US): occasion → (month, day), lead weeks to start publishing.
GIFT_CALENDAR = [
    ("Valentine's Day", (2, 14), 6), ("Mother's Day", (5, 10), 6),
    ("Father's Day", (6, 21), 5), ("Graduation season", (5, 25), 5),
    ("Back to School", (8, 20), 4), ("Halloween", (10, 31), 4),
    ("Thanksgiving", (11, 26), 4), ("Black Friday & Cyber Monday", (11, 27), 5),
    ("Christmas", (12, 25), 7),
]


def _upcoming(today: date, horizon_weeks: int = 8) -> list[str]:
    out = []
    for name, (m, d), lead in GIFT_CALENDAR:
        for yr in (today.year, today.year + 1):
            try:
                occ = date(yr, m, d)
            except ValueError:
                continue
            weeks = (occ - today).days / 7.0
            if 0 <= weeks <= horizon_weeks:
                out.append(name)
                break
    return out



GIFT_TREND_PROMPT = """You are an SEO researcher for iMade4U, a small, low-authority
STORE of PERSONALIZED gifts (engraved jewelry, custom keychains, pet portraits &
memorials, custom home decor). Today: {today}.

imade4u is tiny and can ONLY rank on hyper-specific product-ATTRIBUTE long-tails
that Etsy/Amazon/Pinterest don't target individually. Its own Google data proves
every earned impression carries a specific ATTRIBUTE. So do NOT chase viral
aesthetics — find CURRENT gifting demand and express it as attribute x moment.

WINNING FORMULA (non-negotiable) — product ATTRIBUTE x (occasion | recipient):
1. ATTRIBUTE LEG (REQUIRED, lead with it): a material/gemstone/shape/technique —
   {attributes}
2. SECOND LEG (>=1): an OCCASION (+year if timely) or a RECIPIENT.
USE GOOGLE SEARCH only to confirm the OCCASION/RECIPIENT angle is genuinely
current (an upcoming holiday, a real gifting moment) — NOT to find a viral look.

HARD RULES:
- BAN pure aesthetic/mood framings with no product-search demand: "Coquette",
  "Solar-Punk", "Office Siren", "Gilded Age", "Lemon-Core", "Coastal", "Grandma
  Chic", "Dopamine Decor", "Digital Detox". These earn ZERO clicks — never use.
- BAN bare attribute-less head terms Etsy/Amazon own: "name necklace",
  "custom mug", "personalized gifts". "sterling silver photo projection necklace
  for anniversary" = YES; "trending name necklaces" = NO.
- WRITABILITY: the downstream writer has NO web access — frame around the
  attribute + occasion/recipient (both writable from product titles), never a
  celebrity sighting or an unverifiable event.
- CATALOG REALITY: the match nouns must recall REAL stocked products
  (necklace/bracelet/ring/mug/pillow/ornament/blanket/pet portrait); never a
  format the store lacks (no "soundwave rings", "hologram lockets").
- Every topic writable with our product types: {cats}
- DISTINCT angles, no near-duplicates of: {existing}

Return exactly {n} topics. Reply ONLY with a JSON array (no fence), each:
{{"title": "<attribute x occasion/recipient title, 50-70 chars>",
  "type": "<occasion_guide|recipient_guide|buying_guide>" (NO how_to — trend articles are multi-product gift LISTS),
  "match": "<2-4 SHORT single-word product nouns, e.g. necklace, keychain>",
  "tags": "<2-4 comma tags, lowercase-hyphen>",
  "priority": <80-95>}}
"""

PROMPT = """You are an SEO content planner for iMade4U, a small, low-authority
STORE of PERSONALIZED gifts. Generate {n} DISTINCT gift-guide topics. No near-dupes.

WINNING FORMULA (non-negotiable) — product ATTRIBUTE x (recipient | occasion):
imade4u is tiny; it can ONLY rank on hyper-specific 4-6-word long-tails that big
aggregators (Etsy/Amazon/Pinterest) don't target individually. Its own Google
data proves every earned impression carries a specific product ATTRIBUTE.
1. ATTRIBUTE LEG (REQUIRED, lead with it) — a material/gemstone/shape/technique:
     {attributes}
2. SECOND LEG (>=1 of): a RECIPIENT ("for mom", "for couples", "for daughter",
   "to my man") OR an OCCASION+year ("anniversary", "first father's day",
   "father's day {year}").
Every title MUST have the attribute leg + at least one second leg, and must map
to REAL stocked products in: {cats}

HARD BANS:
- NO bare attribute-less head terms — these are owned by Etsy/Amazon and waste
  our effort: {banned}. "sterling silver photo projection necklace" = YES;
  "name necklace" / "custom mug" / "personalized gifts" = NO.
- NO aesthetic/Pinterest-mood framings with no product-search demand ("Lemon-Core
  Kitchen", "Tennis-Core Chic", "Grandma Chic", "Midimalist Home",
  "Christmas in July", "Dopamine Decor", "Coastal Chic"). These earn ZERO clicks.
- The `match` nouns MUST recall real stocked products (necklace/bracelet/ring/
  mug/pillow/ornament/blanket/pet portrait — the store's actual catalog).
{proven}
USE GOOGLE SEARCH only to confirm a real occasion/recipient angle is current —
not to chase viral aesthetics. {seasonal}

Pillars (article_type): occasion_guide, recipient_guide, pet_memorial,
sympathy_guide, buying_guide.

Do NOT duplicate these existing topics (case-insensitive):
{existing}

Reply ONLY with a JSON array (no markdown fence), each element:
{{"title": "<specific attribute x recipient/occasion title, 50-70 chars>",
  "type": "<one pillar>",
  "match": "<2-4 SHORT single-word product nouns to pick products, e.g. necklace, mug, keychain — NOT phrases like 'custom photo mug'>",
  "tags": "<2-4 comma article tags, lowercase-hyphen>",
  "is_trend": <true only for a REAL current occasion/recipient moment; false for evergreen>,
  "priority": <integer 60-90; attribute+occasion+recipient (3 legs) highest>}}
"""


# Catalog ATTRIBUTES — the proven low-competition NARROWER (the gifts analogue
# of quvii's brand term). Every generated topic must lead with one of these
# (material / gemstone / shape / technique), because imade4u's own GSC shows
# EVERY earned impression carries an attribute long-tail, while bare head terms
# ("name necklace", "custom mug") are owned by Etsy/Amazon/Pinterest.
_ATTRIBUTE_HINTS = (
    "sterling silver, 14k gold, gold vermeil, rose gold, photo projection, "
    "birthstone, baguette, infinity, bar, coordinate/GPS, handwriting, "
    "engraved, celestial/zodiac, octagon, minimalist/dainty, bubble"
)
# Bare head terms Etsy/Amazon own — NEVER target these attribute-less.
_HEAD_TERM_BAN = (
    "name necklace, custom mug, personalized gifts, custom necklace, "
    "photo pillow, custom blanket, personalized jewelry, gift ideas"
)


def _proven_demand(site_id: str, days: int = 30, limit: int = 20) -> str:
    """Real imade4u GSC queries already earning impressions (any position) — the
    PROVEN low-competition demand to EXTEND, so generation grounds on what the
    store already ranks for instead of inventing Pinterest aesthetics. Returns a
    prompt block, or '' if GSC is unavailable (best-effort)."""
    try:
        from datetime import timedelta
        from googleapiclient.discovery import build
        from src.utils.google_oauth import get_user_credentials
        svc = build("searchconsole", "v1", credentials=get_user_credentials(),
                    cache_discovery=False)
        rows = svc.searchanalytics().query(siteUrl="sc-domain:imade4u.com", body={
            "startDate": (date.today() - timedelta(days=days)).isoformat(),
            "endDate": date.today().isoformat(), "dimensions": ["query"],
            "rowLimit": 60}).execute().get("rows", [])
        # keep multi-word commercial queries, drop brand-navigational noise
        skip = {"ima4u", "imade it", "md4u", "imaderp foryou", "imade4u"}
        qs = [r["keys"][0] for r in rows
              if r["keys"][0].lower() not in skip and len(r["keys"][0].split()) >= 2]
        if not qs:
            return ""
        return ("\nPROVEN DEMAND — imade4u ALREADY earns impressions for these real "
                "queries (extend/adjacent them; do NOT invent aesthetics unrelated "
                "to these):\n" + "\n".join(f"  - {q}" for q in qs[:limit]) + "\n")
    except Exception:  # noqa: BLE001 — grounding is a bonus, never fatal
        return ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", type=int, default=15)
    ap.add_argument("--min-planned", type=int, default=12)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--model", default="gemini-3-flash-preview")
    args = ap.parse_args()

    with get_db_connection() as conn, conn.cursor() as cur:
        cur.execute("select id from sites where domain='imade4u.com'")
        row = cur.fetchone()
        if not row:
            print("❌ imade4u tenant missing"); return 2
        site_id = str(row[0])
        cur.execute("select count(*) from keywords where site_id=%s and status='planned'", (site_id,))
        planned = cur.fetchone()[0]
        cur.execute("select keyword from keywords where site_id=%s order by created_at desc limit 60", (site_id,))
        existing = [r[0] for r in cur.fetchall()]

    # Fetch the real GSC proven-demand block ONCE and share it (one API call for
    # both the trend scan and the top-up prompt).
    proven = _proven_demand(site_id)

    # ── 独立热点扫描(对齐 ntecodex):无条件、自门控(≥11h),每次产
    # 6-8 个 source='trend' 话题。供给侧保证 imade4u 跟上实时热点 ——
    # 此前热点只在池子低于阈值时顺带产出,导致全站几乎零热点文章。
    try:
        from scripts.keyword_gardener import _last_trend_scan_hours_ago, _mark_trend_scan
        ago = _last_trend_scan_hours_ago(site_id)
        if ago is not None and ago < 11:
            print(f"  📈 gift trend scan: skipped — last {ago:.1f}h ago")
        else:
            _gift_trend_scan(site_id, existing, args, proven)
            _mark_trend_scan(site_id)
    except Exception as _e:  # noqa: BLE001 — trend layer must never break top-up
        print(f"  ⚠️  gift trend scan failed: {type(_e).__name__}: {_e}")

    if planned >= args.min_planned and not args.force:
        print(f"  pool healthy ({planned} planned ≥ {args.min_planned}) — no top-up"); return 0

    occ = _upcoming(date.today())
    seasonal = (f"SEASONAL FOCUS — these gift occasions are approaching; weight "
                f"~half the topics toward them with priority 80-90: {', '.join(occ)}."
                if occ else "No major gift occasion is imminent; focus on evergreen "
                "pillars (pet memorial, sympathy, recipient, buying guides).")
    prompt = PROMPT.format(n=args.target, cats=PRODUCT_CATS, seasonal=seasonal,
                           year=date.today().year, attributes=_ATTRIBUTE_HINTS,
                           banned=_HEAD_TERM_BAN, proven=proven,
                           existing="\n".join(f"  - {k}" for k in existing[:50]) or "  (none)")

    # Self-improvement loop: inject the latest AI guidance (from qdf_report's
    # retrospective on how imade4u's trend pages performed) so topic selection
    # learns what actually wins traffic.
    try:
        from src.utils.qdf_memory import latest_qdf_guidance
        g = latest_qdf_guidance(site_id)
        if g:
            prompt += ("\n\nLEARNINGS FROM OUR RECENT PERFORMANCE (apply these — "
                       "derived from how our last gift trend posts actually did):\n" + g + "\n")
            print("   🧠 injected prior QDF guidance")
    except Exception:
        pass

    # enable_search → real current gift trends (grounding forces json_mode off;
    # the parse below handles fenced / array output).
    resp = get_llm_provider("gemini").generate(
        prompt=prompt, model=args.model, max_tokens=4000, temperature=0.7,
        json_mode=False, enable_search=True)
    text = (resp.text or "").strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0]
    try:
        data = json.loads(text)
    except Exception:
        i, j = text.find("["), text.rfind("]")
        try:
            data = json.loads(text[i:j + 1]) if i >= 0 else []
        except Exception:
            # grounded gemini-flash prepends prose / truncates → salvage objects
            import re as _re
            data = []
            for m in _re.findall(r"\{[^{}]*\}", text):
                try:
                    data.append(json.loads(m))
                except Exception:
                    continue
            if data:
                print(f"   ⚠️  top-up salvaged {len(data)} object(s)")
    if isinstance(data, dict):
        data = next((v for v in data.values() if isinstance(v, list)), [])

    have = {k.lower() for k in existing}
    nonrend = "gift_seasonal" if occ else "gift_topup"
    inserted = ntrend = 0
    valid_types = {"occasion_guide", "recipient_guide", "pet_memorial",
                   "sympathy_guide", "buying_guide", "how_to"}
    with get_db_connection(autocommit=True) as conn, conn.cursor() as cur:
        for it in data:
            if not isinstance(it, dict):
                continue
            title = (it.get("title") or "").strip()
            atype = it.get("type") if it.get("type") in valid_types else "buying_guide"
            if not title or title.lower() in have or not it.get("match"):
                continue
            # Real-time trends → source='trend' so qdf_report tracks them and
            # the AI retrospective loop can learn from their performance.
            row_src = "trend" if it.get("is_trend") else nonrend
            notes = f"type={atype}|match={it.get('match')}|tags={it.get('tags','personalized-gifts')}"
            cur.execute(
                "insert into keywords (site_id, keyword, intent, priority_score, source, notes, status) "
                "values (%s,%s,'commercial',%s,%s,%s,'planned') on conflict (site_id, keyword) do nothing",
                (site_id, title, int(it.get("priority") or 65), row_src, notes))
            if cur.rowcount:
                inserted += 1
                if row_src == "trend":
                    ntrend += 1
                have.add(title.lower())
    print(f"  ✓ imade4u top-up: +{inserted} topics ({ntrend} real-time trend, "
          f"{'seasonal: '+', '.join(occ) if occ else 'evergreen'}) cost ${resp.cost_usd:.4f}")
    return 0




def _gift_trend_scan(site_id, existing: list, args, proven: str = "") -> int:
    """Grounded real-time gift-trend scan → source='trend' topics (the supply
    half of the ntecodex QDF pattern; the demand half is the freshness bonus
    in content_imade4u's picker). `proven` = the shared GSC proven-demand block."""
    import json as _json
    from src.utils.llm import get_llm_provider
    prompt = GIFT_TREND_PROMPT.format(
        today=date.today().isoformat(), cats=PRODUCT_CATS, n=8,
        attributes=_ATTRIBUTE_HINTS,
        existing=", ".join(list(existing)[:30]) or "(none)")
    prompt += proven
    try:
        from src.utils.qdf_memory import latest_qdf_guidance
        g = latest_qdf_guidance(site_id)
        if g:
            prompt += "\n\nLEARNINGS FROM OUR RECENT PERFORMANCE (apply):\n" + g
            print("  🧠 injected QDF guidance into gift trend scan")
    except Exception:
        pass
    resp = get_llm_provider("gemini").generate(
        prompt=prompt, model=args.model, max_tokens=4000, temperature=0.6,
        json_mode=False, enable_search=True)
    t = (resp.text or "").strip()
    if t.startswith("```"):
        t = t.split("\n", 1)[-1].rsplit("```", 1)[0]
    i, j = t.find("["), t.rfind("]")
    try:
        data = _json.loads(t[i:j + 1]) if i >= 0 else []
    except Exception:
        # Grounded gemini-flash often prepends prose / truncates the array —
        # salvage every COMPLETE {...} object rather than lose the whole scan.
        import re as _re
        data = []
        for m in _re.findall(r"\{[^{}]*\}", t):
            try:
                data.append(_json.loads(m))
            except Exception:
                continue
        if data:
            print(f"  ⚠️  trend output salvaged {len(data)} object(s)")
        else:
            print("  ⚠️  gift trend parse failed"); return 0
    have = {k.lower() for k in existing}
    valid = {"occasion_guide", "recipient_guide", "buying_guide"}
    n = 0
    with get_db_connection(autocommit=True) as conn, conn.cursor() as cur:
        for it in data:
            if not isinstance(it, dict):
                continue
            title = (it.get("title") or "").strip()
            if not title or title.lower() in have or not it.get("match"):
                continue
            atype = it.get("type") if it.get("type") in valid else "buying_guide"
            notes = f"type={atype}|match={it.get('match')}|tags={it.get('tags','trending-gifts')}"
            # Catalog-reality check: the match terms must recall >=5 real
            # products, else the writer can't fulfil the title (bait-and-
            # switch) — skip the topic instead of wasting a generation.
            try:
                from scripts.gift_sample import _products as _gp
                if len(_gp([m for m in str(it.get("match")).split(",") if m])) < 5:
                    print(f"    ⏭  catalog-reality skip: {title[:50]!r}")
                    continue
            except Exception:
                pass
            cur.execute(
                "insert into keywords (site_id, keyword, intent, priority_score, source, notes, status) "
                "values (%s,%s,'commercial',%s,'trend',%s,'planned') on conflict (site_id, keyword) do nothing",
                (str(site_id), title, int(it.get("priority") or 85), notes))
            if cur.rowcount:
                n += 1; have.add(title.lower())
    print(f"  📈 gift trend scan: +{n} trend topics (cost ${resp.cost_usd:.4f})")
    return n


if __name__ == "__main__":
    raise SystemExit(main())
