"""Inject per-site public IDs into the Astro build environment.

Runs BEFORE `npm run build` in each site's workflow. Queries
sites.config for non-secret tracking IDs (GA4 measurement, AdSense
publisher) and writes them to <site_repo>/.env.local so Astro picks
them up via `import.meta.env.PUBLIC_*`.

Two-tier lookup (same fallback chain as src.collectors.base.get_site_value):
  1. sites.config.<key>          ← Dashboard-editable, takes effect
                                    on the very next deploy
  2. <SLUG>_<KEY_UPPER> env var   ← legacy / fallback

Writing to .env.local rather than `process.env`:
  - Astro reads .env.local at build time for any PUBLIC_* var.
  - The file is short-lived (each cron rebuilds it from DB) so a stale
    edit in the file never overrides DB.

Usage (called from the workflow):
    SITE_DOMAIN=pixelmatch.art SITE_REPO_PATH=$GITHUB_WORKSPACE/pixelmatch-site \
        python -m scripts.inject_site_env
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from src.db.client import get_db_connection

load_dotenv(Path(__file__).resolve().parent.parent / ".env")


# (db_key, env_key, public_name, default)
# public_name is what Astro sees as `import.meta.env.PUBLIC_<name>`.
TRACKED_FIELDS: list[tuple[str, str, str, Optional[str]]] = [
    ("ga4_measurement_id",   "GA4_MEASUREMENT_ID",   "PUBLIC_GA_MEASUREMENT_ID", None),
    ("adsense_publisher_id", "ADSENSE_PUBLISHER_ID", "PUBLIC_ADSENSE_PUB_ID",    None),
]


def main() -> int:
    site_domain = os.getenv("SITE_DOMAIN", "ntecodex.com")
    site_repo_path = os.getenv("SITE_REPO_PATH")
    if not site_repo_path:
        # Local dev convenience: assume sibling layout
        here = Path(__file__).resolve()
        guess = here.parent.parent.parent / f"{site_domain.split('.')[0]}-site"
        if guess.exists():
            site_repo_path = str(guess)
        else:
            print(f"❌ SITE_REPO_PATH not set and no sibling repo at {guess}")
            return 2

    site_repo = Path(site_repo_path).resolve()
    if not site_repo.exists():
        print(f"❌ site repo not found: {site_repo}")
        return 2

    with get_db_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "select id, config from sites where domain = %s limit 1",
            (site_domain,),
        )
        row = cur.fetchone()
        if not row:
            print(f"❌ site {site_domain!r} not in sites table")
            return 2
        _site_id, config = row

    cfg = config or {}
    slug = (cfg.get("site_slug") or "").upper().replace("-", "_")

    lines: list[str] = []
    lines.append(f"# Generated by scripts.inject_site_env for {site_domain}")
    lines.append("# Two-tier lookup: sites.config.<key> first, then <SLUG>_<KEY> env.")
    lines.append("# DO NOT EDIT — overwritten on every build.")

    resolved: dict[str, str] = {}
    for db_key, env_key, public_name, default in TRACKED_FIELDS:
        # Try DB first
        val = cfg.get(db_key)
        source = "DB"
        if not val and slug:
            val = os.getenv(f"{slug}_{env_key}")
            source = "env"
        if not val:
            val = default
            source = "default"
        if val:
            lines.append(f"{public_name}={val}      # source: {source}")
            resolved[public_name] = f"{val} ({source})"
        else:
            lines.append(f"# {public_name}=(unset — neither DB nor env had a value)")
            resolved[public_name] = "(unset)"

    out_path = site_repo / ".env.local"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"✓ wrote {out_path}")
    for k, v in resolved.items():
        print(f"   {k:30s} → {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
