"""QAAgent — score article on 6 dimensions including factual_accuracy.

Uses qa_model (Pro) with Google Search grounding so the reviewer
independently verifies proper nouns the writer claimed.
"""

from __future__ import annotations

import json
from typing import Any

from src.agents._json_extract import extract_json
from src.agents.base import BaseAgent


FACTUAL_RULES = """
CRITICAL FACT-CHECK RULES:
1. This article is about {game_name} ({game_abbr}), released on {release_date}.
2. The writer was instructed to use Google Search. Now verify their work.
3. Identify ALL proper nouns claimed in the article: character names, weapon
   names, skill names, system / mechanic names, banner names.
4. For each, run a Google search. If a name returns NO {game_name}-related
   results from gaming sites or social media, treat it as fabricated.
5. Even one fabricated proper noun => factual_accuracy = 0 and passed = false.
   Multiple confirmed real names but with fabricated mechanics => max 1.0.
6. Prefer official sources, IGN, GameSpot, Polygon, Game8, Game Rant, Reddit.
"""


PROMPT = """You are a strict editorial QA reviewer for a {game_name} guide site.
The article was generated by ANOTHER LLM (Flash). Your job is to find its
weak spots, NOT to be polite. The writer cuts corners — your job is to catch them.

{factual_rules}

Target keyword (search intent): {keyword}
Article type: {article_type}
Required word range: {min_words}-{max_words} (actual: {actual_words})
Outline that the writer was supposed to follow:
{outline_json}

Article content (Markdown):
---
{content}
---

Score on 6 dimensions, each 0-2 (total 0-12, then divide by 1.2 to map to 0-10):
1. intent_match: does the article actually answer the search query?
2. info_density: concrete numbers, tables, lists vs vague filler?
3. structure: matches outline order, clear H2/H3 hierarchy, has Sources section?
4. ai_pattern: free of stock AI phrasing? (deduct for "delve into", "in the
   realm of", "embark", "navigating", "in today's fast-paced", "remember that",
   "it's important to note")
5. seo: H1 contains keyword? Internal-link anchors use the
   `#TODO:keyword:` format? No example.com? Meta-friendly?
6. factual_accuracy: every proper noun verified via search? Score 0 if any
   character / weapon / mechanic name appears fabricated. Score 1 if names
   are real but mechanics or numbers seem invented. Score 2 if all major
   claims are corroborated.

Pass threshold: total/1.2 >= {pass_threshold}.

Reply with a single JSON object (no surrounding prose, no fences). Schema:
{{
  "score_raw_12": <float 0-12>,
  "score": <float 0-10, equals score_raw_12 / 1.2>,
  "passed": <bool>,
  "feedback": {{
    "intent_match":     <0-2 float>,
    "info_density":     <0-2 float>,
    "structure":        <0-2 float>,
    "ai_pattern":       <0-2 float>,
    "seo":              <0-2 float>,
    "factual_accuracy": <0-2 float>,
    "fabricated_terms": ["<term that did not verify>", "..."],
    "verified_terms":   ["<term that did verify>", "..."],
    "issues":           ["<concrete issue>", "..."],
    "suggestions":      ["<actionable rewrite tip>", "..."]
  }}
}}
"""


class QAAgent(BaseAgent):
    name = "qa"
    task_type = "qa"
    max_retries = 1

    def _execute(self, input_data: dict[str, Any]) -> dict[str, Any]:
        keyword = input_data["keyword"]
        article_type = input_data["article_type"]
        content = input_data["content_md"]
        outline = input_data["outline"]
        actual_words = int(input_data.get("word_count", 0))
        min_words = int(input_data.get("min_word_count", 1200))
        max_words = int(input_data.get("max_word_count", 2500))
        pass_threshold = float(self.site_config["qa_thresholds"]["min_quality_score"])

        game = self.site_config.get("game", {})
        rules = FACTUAL_RULES.format(
            game_name=game.get("name", "the game"),
            game_abbr=game.get("abbreviation", ""),
            release_date=game.get("release_date", "recently"),
        )

        prompt = PROMPT.format(
            game_name=game.get("name", "the game"),
            factual_rules=rules,
            keyword=keyword,
            article_type=article_type,
            min_words=min_words,
            max_words=max_words,
            actual_words=actual_words,
            outline_json=json.dumps(outline, indent=2, ensure_ascii=False),
            content=content,
            pass_threshold=pass_threshold,
        )

        resp = self._call_llm(
            prompt=prompt,
            max_tokens=8000,
            temperature=0.2,
            json_mode=True,           # auto-dropped when enable_search=True
            enable_search=True,
        )
        result = extract_json(resp.text)

        # Re-derive score from the 6 dims to defend against LLM math errors
        feedback = result.get("feedback", {}) or {}
        dim_keys = ("intent_match", "info_density", "structure",
                    "ai_pattern", "seo", "factual_accuracy")
        try:
            raw_12 = sum(float(feedback.get(k, 0)) for k in dim_keys)
        except (TypeError, ValueError):
            raw_12 = float(result.get("score_raw_12", 0) or 0)
        score = round(raw_12 / 1.2, 2)

        # Hard rule: any fabricated_terms => fail regardless of score
        fabricated = feedback.get("fabricated_terms") or []
        passed = (score >= pass_threshold) and not fabricated

        return {
            "score": score,
            "score_raw_12": raw_12,
            "passed": passed,
            "pass_threshold": pass_threshold,
            "feedback": feedback,
        }
