"""QAAgent — score article, recommend pass/fail. Uses qa_model (Pro)."""

from __future__ import annotations

import json
from typing import Any

from src.agents.base import BaseAgent


PROMPT = """You are a strict editorial QA reviewer for a gacha-game guide site.
The article was generated by ANOTHER LLM (Flash). Your job is to find its
weak spots, not to be polite.

Target keyword (search intent): {keyword}
Article type: {article_type}
Required word range: {min_words}-{max_words} (actual: {actual_words})
Outline that the writer was supposed to follow:
{outline_json}

Article content (Markdown):
---
{content}
---

Score on 5 dimensions, each 0-2. Total = sum (0-10).
1. intent_match: does the article actually answer the search query?
2. info_density: concrete numbers, tables, lists vs vague filler?
3. structure: matches outline order, clear H2/H3 hierarchy?
4. ai_pattern: free of stock AI phrasing? (deduct for "delve into", "in the
   realm of", "embark", "navigating", "in today's fast-paced", excessive
   "remember that", "it's important to note")
5. seo: H1 contains keyword? Internal-link anchors look natural? Meta-friendly?

Pass threshold: total >= {pass_threshold}.

Reply with JSON only (no markdown fence). Schema:
{{
  "score": <float 0-10>,
  "passed": <bool>,
  "feedback": {{
    "intent_match":  <0-2 float>,
    "info_density":  <0-2 float>,
    "structure":     <0-2 float>,
    "ai_pattern":    <0-2 float>,
    "seo":           <0-2 float>,
    "issues":      ["<concrete issue>", "..."],
    "suggestions": ["<actionable rewrite tip>", "..."]
  }}
}}
"""


class QAAgent(BaseAgent):
    name = "qa"
    task_type = "qa"
    max_retries = 1   # QA itself shouldn't retry on transient API; orchestrator handles writing-rewrite

    def _execute(self, input_data: dict[str, Any]) -> dict[str, Any]:
        keyword = input_data["keyword"]
        article_type = input_data["article_type"]
        content = input_data["content_md"]
        outline = input_data["outline"]
        actual_words = int(input_data.get("word_count", 0))
        min_words = int(input_data.get("min_word_count", 1200))
        max_words = int(input_data.get("max_word_count", 2500))
        pass_threshold = float(
            self.site_config["qa_thresholds"]["min_quality_score"]
        )

        prompt = PROMPT.format(
            keyword=keyword,
            article_type=article_type,
            min_words=min_words,
            max_words=max_words,
            actual_words=actual_words,
            outline_json=json.dumps(outline, indent=2, ensure_ascii=False),
            content=content,
            pass_threshold=pass_threshold,
        )

        resp = self._call_llm(
            prompt=prompt, max_tokens=8000, temperature=0.2, json_mode=True,
        )
        result = json.loads(resp.text)

        for required in ("score", "passed", "feedback"):
            if required not in result:
                raise ValueError(f"QA output missing field: {required}")

        # Re-derive pass from threshold to be safe (don't trust LLM's bool)
        result["passed"] = float(result["score"]) >= pass_threshold
        result["pass_threshold"] = pass_threshold
        return result
