"""QAAgent — score article on 6 dimensions including factual_accuracy.

Uses qa_model (Pro) with Google Search grounding so the reviewer
independently verifies proper nouns the writer claimed.
"""

from __future__ import annotations

import json
import re
from typing import Any

from src.agents._json_extract import extract_json
from src.agents.base import BaseAgent


# Matches the writer's sanctioned "I cannot verify this" placeholder.
# Tolerant: the date suffix is optional / variable, and the QA LLM may
# echo back a slightly different casing or trim.
_HONESTY_PLACEHOLDER_RE = re.compile(
    r"\[?\s*information not yet publicly available"
    r"(?:\s+as of[^\]]*?)?\s*\]?",
    re.IGNORECASE,
)


def _is_honesty_placeholder(term: str) -> bool:
    """Return True when a fabricated_terms entry is actually the
    sanctioned honesty placeholder rather than a real fabrication."""
    if not isinstance(term, str):
        return False
    return bool(_HONESTY_PLACEHOLDER_RE.search(term))


FACTUAL_RULES = """
CRITICAL FACT-CHECK RULES:
1. This article is about {game_name} ({game_abbr}), released on {release_date}.
2. The writer was instructed to use Google Search. Now verify their work.
3. Identify ALL proper nouns claimed in the article: character names, weapon
   names, skill names, system / mechanic names, banner names.
4. For each, run a Google search. If a name returns NO {game_name}-related
   results from gaming sites or social media, treat it as fabricated.
5. Even one fabricated proper noun => factual_accuracy = 0 and passed = false.
   Multiple confirmed real names but with fabricated mechanics => max 1.0.
6. Prefer official sources, IGN, GameSpot, Polygon, Game8, Game Rant, Reddit.

HONESTY PLACEHOLDER RULE (added 2026-05-11):
   The writer is INSTRUCTED to write the literal phrase
   "[Information not yet publicly available as of YYYY-MM-DD]" when a
   specific fact (number, mechanic, banner name) cannot be verified via
   search. This is the CORRECT behavior — not a fabrication.

   - DO NOT add the placeholder string itself to `fabricated_terms`.
   - DO NOT lower factual_accuracy for the presence of placeholders.
   - You MAY (and should) lower `info_density` if the article has too
     many placeholders for it to be a useful guide — that's the right
     scoring channel for "honest but thin" content.
   - If you find a placeholder where the information IS actually
     publicly available (you can verify it via search), that's a
     writer failure: list it under `issues` as a missed-research
     instance but still don't treat the placeholder as fabricated.
"""


PROMPT = """You are a strict editorial QA reviewer for a {game_name} guide site.
The article was generated by ANOTHER LLM (Flash). Your job is to find its
weak spots, NOT to be polite. The writer cuts corners — your job is to catch them.

{factual_rules}

Target keyword (search intent): {keyword}
Article type: {article_type}
Required word range: {min_words}-{max_words} (actual: {actual_words})
Outline that the writer was supposed to follow:
{outline_json}

Article content (Markdown):
---
{content}
---

Score on 6 dimensions, each 0-2 (total 0-12, then divide by 1.2 to map to 0-10):
1. intent_match: does the article actually answer the search query?
2. info_density: concrete numbers, tables, lists vs vague filler?
3. structure: matches outline order, clear H2/H3 hierarchy, has Sources section?
4. ai_pattern: free of stock AI phrasing? (deduct for "delve into", "in the
   realm of", "embark", "navigating", "in today's fast-paced", "remember that",
   "it's important to note")
5. seo: H1 contains keyword? No example.com? Meta-friendly title?
   NOTE: do NOT penalize for missing internal links — those are added
   automatically by PublishAgent's _internal_links module AFTER writing.
   The writer is explicitly forbidden from inserting them (would create
   double-links). Score this dimension on H1 keyword presence, content
   structure for SERP previews, and absence of placeholder URLs only.
6. factual_accuracy: every proper noun verified via search? Score 0 if any
   character / weapon / mechanic name appears fabricated. Score 1 if names
   are real but mechanics or numbers seem invented. Score 2 if all major
   claims are corroborated.

Pass threshold: total/1.2 >= {pass_threshold}.

Reply with a single JSON object (no surrounding prose, no fences). Schema:
{{
  "score_raw_12": <float 0-12>,
  "score": <float 0-10, equals score_raw_12 / 1.2>,
  "passed": <bool>,
  "feedback": {{
    "intent_match":     <0-2 float>,
    "info_density":     <0-2 float>,
    "structure":        <0-2 float>,
    "ai_pattern":       <0-2 float>,
    "seo":              <0-2 float>,
    "factual_accuracy": <0-2 float>,
    "fabricated_terms": ["<term that did not verify>", "..."],
    "verified_terms":   ["<term that did verify>", "..."],
    "issues":           ["<concrete issue>", "..."],
    "suggestions":      ["<actionable rewrite tip>", "..."]
  }}
}}
"""


class QAAgent(BaseAgent):
    name = "qa"
    task_type = "qa"
    max_retries = 1

    def _execute(self, input_data: dict[str, Any]) -> dict[str, Any]:
        keyword = input_data["keyword"]
        article_type = input_data["article_type"]
        content = input_data["content_md"]
        outline = input_data["outline"]
        actual_words = int(input_data.get("word_count", 0))
        min_words = int(input_data.get("min_word_count", 1200))
        max_words = int(input_data.get("max_word_count", 2500))
        pass_threshold = float(self.site_config["qa_thresholds"]["min_quality_score"])

        # Multi-game (P0 fix 2026-05-13): read game from input_data and look
        # up game_metadata. Without this, QA verifies every WuWa / HSR /
        # ZZZ proper noun against "Neverness to Everness" and finds zero
        # results → flags real entities (Jiyan, Ruan Mei, Anby Demara) as
        # fabricated → 100% qa_failed across all multi-game articles.
        # This was the missing piece in Phase 2.3 — Outline + Writing got
        # the threading, QA didn't.
        game_slug = input_data.get("game") or "unknown"
        game_meta_by_slug = self.site_config.get("game_metadata") or {}
        per_game = game_meta_by_slug.get(game_slug) or {}
        legacy_game = self.site_config.get("game") or {}
        game_name = (
            per_game.get("display_name")
            or legacy_game.get("name")
            or "the game"
        )
        game_abbr = (
            per_game.get("short_name")
            or legacy_game.get("abbreviation")
            or game_slug
        )
        release_date = (
            per_game.get("release_date")
            or legacy_game.get("release_date")
            or "recently"
        )
        rules = FACTUAL_RULES.format(
            game_name=game_name,
            game_abbr=game_abbr,
            release_date=release_date,
        )

        prompt = PROMPT.format(
            game_name=game_name,
            factual_rules=rules,
            keyword=keyword,
            article_type=article_type,
            min_words=min_words,
            max_words=max_words,
            actual_words=actual_words,
            outline_json=json.dumps(outline, indent=2, ensure_ascii=False),
            content=content,
            pass_threshold=pass_threshold,
        )

        resp = self._call_llm(
            prompt=prompt,
            max_tokens=8000,
            temperature=0.2,
            json_mode=True,           # auto-dropped when enable_search=True
            enable_search=True,
        )
        result = extract_json(resp.text)

        # Re-derive score from the 6 dims to defend against LLM math errors
        feedback = result.get("feedback", {}) or {}
        dim_keys = ("intent_match", "info_density", "structure",
                    "ai_pattern", "seo", "factual_accuracy")
        try:
            raw_12 = sum(float(feedback.get(k, 0)) for k in dim_keys)
        except (TypeError, ValueError):
            raw_12 = float(result.get("score_raw_12", 0) or 0)
        score = round(raw_12 / 1.2, 2)

        # Post-hoc filter: even with the explicit HONESTY PLACEHOLDER
        # RULE in the prompt, the QA LLM occasionally lists the literal
        # honesty placeholder string as a fabricated_term. That's a
        # category error the writer shouldn't be punished for — the
        # placeholder is the SANCTIONED way to admit a knowledge gap.
        # Strip it out before applying the hard rule below.
        fabricated_raw = feedback.get("fabricated_terms") or []
        fabricated = [
            t for t in fabricated_raw
            if not _is_honesty_placeholder(t)
        ]
        stripped = [t for t in fabricated_raw if _is_honesty_placeholder(t)]
        if stripped:
            # Keep an audit trail in the feedback dict so we can tell
            # post-hoc that the LLM did flag the placeholder.
            feedback["fabricated_terms"] = fabricated
            feedback["_honesty_placeholder_stripped"] = stripped

        # Hard-fail rule (softened 2026-05-13 P0):
        #
        # Original: ANY fabricated_term auto-failed the article. That was
        # correct when most failures were full hallucination (Phase 2.3
        # NTE-pivot articles). After the multi-game pivot the dominant
        # failure mode is "writer got the game + character right, named
        # ONE supporting trace/material/skill close-but-wrong" — e.g.
        # Robin's ult is `Pinion's Aria` not `Aria of Featherlight`,
        # Argenti's stack is `Apotheosis` not `Apostle`. These articles
        # have factual_accuracy=2.0 on the verified majority but the
        # hard rule killed them anyway, leaving pass-rate at ~17%.
        #
        # New rule: allow at most ONE fabricated term IF factual_accuracy
        # is still strong (≥1.0). Articles with multiple fabrications or
        # zero factual_accuracy still hard-fail. QA still surfaces the
        # term in feedback for audit; the operator can rewrite it later.
        try:
            fa = float(feedback.get("factual_accuracy") or 0)
        except (TypeError, ValueError):
            fa = 0.0
        hard_fail = len(fabricated) >= 2 or fa < 1.0
        passed = (score >= pass_threshold) and not hard_fail
        if fabricated and not hard_fail:
            feedback["_borderline_fabrications_allowed"] = fabricated

        return {
            "score": score,
            "score_raw_12": raw_12,
            "passed": passed,
            "pass_threshold": pass_threshold,
            "feedback": feedback,
        }
